### ISSUE TITLE
[Refactor] 유저의 공개/비공개 필드로 goal 조회 가능 여부 설정과 LifeMap의 분리

### ISSUE THREAD

**Issue by binary-ho** [depromeet/amazing3-be#69]
### ⚠️ Issue
유저의 공개/비공개 필드를 추가하고, 공개/비공개 필드를 통해 Goal 공개 여부를 설정할 수 있게 한다.
기존엔 유저가 Goal을 조회할 때, 자신의 Goal에 대한 조회 요청이 맞는지 확인했다. <br> **공개;/비공개 필드 추가 이후엔, 해당 검사 로직을 삭제하겠다** <br> <br> 애초에, 팔로우-팔로워가 아닌 공개/비공개 필드로 지도의 공개 여부를 정하는 순간 부터, 유저의 goal들은 "공개" 설정시 username만 때려 맞춘다면 모두가 볼 수 있다. <br> 
따라서, 인생 지도 "공개"로 설정시 유저의 goal이 public 상태로 되는 것은 부자연스럽지 않다. 

# 01/05 추가 명세
유저들의 지도를 분리하기로 결정했다.
지도의 공개/비공개 필드를 유저가 가지고 있는 것은 어색하고 지도가 가지고 있어야 한다고 회의때 결론이 났다.
애초에 기존처럼 유저가 가지고 있는 경우, 공개 여부는 유저 테이블에, Goals는 다른 테이블에 있어 단순 JPA 메서드 이나, @Query로는 한번에 가져오기가 힘들었다. 

엔티티 메니저에 직접 쿼리를 넣어야 했고, 그렇게 개발했는데, LifeMap을 분리하기로 결정이 났다.

LifeMap이란, 유저의 인생 지도에 포함된 목표들과 그 공개 여부를 가진 객체이다.
이러한 구현은 추후 확장을 고려했을 때도 좋다. 
유저별로 분야별로 여러 LifeMap을 가질 수도 있기 때문이다.
결론적으로 아래와 같이 수정하려 한다

![bandibudierd drawio](https://github.com/depromeet/amazing3-be/assets/71186266/fd19e7a6-641b-4e30-a797-54ee78834200)

## TODO
- [x] User에 인생지도 공개/비공개 필드 추가
- [x] 다른 사람의 전체 목표를 조회하는 API 구현
- [x] Goal 조회시 요청한 유저 검증 로직 제거
- [x] 위 기능들에 대한 테스트 코드 추가
